var searchData=
[
  ['tasser_5ftab_0',['tasser_tab',['../tab__character_8c.html#a7385dcda8ffa6298eef3e75eb4030df7',1,'tasser_tab(tab_charactere_t **characters, int nb_mort):&#160;tab_character.c'],['../tab__character_8h.html#a7385dcda8ffa6298eef3e75eb4030df7',1,'tasser_tab(tab_charactere_t **characters, int nb_mort):&#160;tab_character.c']]],
  ['temp_5fformer_1',['temp_former',['../character_8c.html#a6c78f57bff1cf189754f1eb47438fe96',1,'character.c']]],
  ['touches_2',['touches',['../gestion_8c.html#a78a065eeb4d024efdafada7c4ca943bf',1,'touches(SDL_Event evenement, int *textInputActive, int *keyCounts, int *isValid, char *textInput, const char *ipPattern, int *valide):&#160;gestion.c'],['../gestion_8h.html#a78a065eeb4d024efdafada7c4ca943bf',1,'touches(SDL_Event evenement, int *textInputActive, int *keyCounts, int *isValid, char *textInput, const char *ipPattern, int *valide):&#160;gestion.c']]],
  ['traitement_5fen_5fjeu_3',['traitement_en_jeu',['../gestion_8c.html#a9dbe2557ebf663ede9aef1103c752222',1,'traitement_en_jeu(etat_t *etat, player_t **j1, player_t **j2_distant, ordi_t **o, Uint32 *diff_time, Uint32 *lastUlti, Uint32 *delai_ulti, int *reseau_action, int *reseau_action2, int *to_server_socket, int *client_socket, character_t *tab_de_charactere, SDL_Renderer *rendu, SDL_Rect *playerImg, SDL_Rect *ordiImg, SDL_Rect *playerAttackImg, SDL_Rect *ordiAttackImg, int *first_attaque, SDL_Rect playerPosition[], SDL_Rect ordiPosition[], int *ancien_lvl, SDL_Texture *image[], SDL_Texture *img_char[], Uint32 currentTime, Uint32 *lastMovement, int w, int h, int *cameraX, int *cameraY, unsigned long int *debut_sprite, unsigned long int *fin_sprite, SDL_Texture *img_c_ordi[]):&#160;gestion.c'],['../gestion_8h.html#a9dbe2557ebf663ede9aef1103c752222',1,'traitement_en_jeu(etat_t *etat, player_t **j1, player_t **j2_distant, ordi_t **o, Uint32 *diff_time, Uint32 *lastUlti, Uint32 *delai_ulti, int *reseau_action, int *reseau_action2, int *to_server_socket, int *client_socket, character_t *tab_de_charactere, SDL_Renderer *rendu, SDL_Rect *playerImg, SDL_Rect *ordiImg, SDL_Rect *playerAttackImg, SDL_Rect *ordiAttackImg, int *first_attaque, SDL_Rect playerPosition[], SDL_Rect ordiPosition[], int *ancien_lvl, SDL_Texture *image[], SDL_Texture *img_char[], Uint32 currentTime, Uint32 *lastMovement, int w, int h, int *cameraX, int *cameraY, unsigned long int *debut_sprite, unsigned long int *fin_sprite, SDL_Texture *img_c_ordi[]):&#160;gestion.c']]],
  ['traitement_5fpost_5fjeu_4',['traitement_post_jeu',['../gestion_8c.html#a56978e1226d064639c5e4dcbca149af9',1,'traitement_post_jeu(character_t **tab_de_charactere, player_t **j1, player_t **j2_distant, ordi_t **o, int *cameraX, int *cameraY, char *buffer, int *survol, Uint32 *lastUlti, Uint32 *diff_time, Uint32 *delai_ulti, int *reseau_action, int *reseau_action2, int *troupe_formee[], int *nb[], Uint32 *lastTroupe[], Mix_Chunk *musique_fin, int *ancien_lvl):&#160;gestion.c'],['../gestion_8h.html#a56978e1226d064639c5e4dcbca149af9',1,'traitement_post_jeu(character_t **tab_de_charactere, player_t **j1, player_t **j2_distant, ordi_t **o, int *cameraX, int *cameraY, char *buffer, int *survol, Uint32 *lastUlti, Uint32 *diff_time, Uint32 *delai_ulti, int *reseau_action, int *reseau_action2, int *troupe_formee[], int *nb[], Uint32 *lastTroupe[], Mix_Chunk *musique_fin, int *ancien_lvl):&#160;gestion.c']]],
  ['traitement_5fpre_5fjeu_5',['traitement_pre_jeu',['../gestion_8c.html#aea96c8a533b3bc1c6350aa557ce09825',1,'traitement_pre_jeu(etat_t *etat, int *a_deja_lancer_partie, player_t **j1, ordi_t **o, player_t *j2_distant, SDL_Texture *image[], int *ancien_lvl, character_t *tab_de_charactere, int *connexion_reussi, int *valide, int *resultat, SDL_Renderer *rendu):&#160;gestion.c'],['../gestion_8h.html#aea96c8a533b3bc1c6350aa557ce09825',1,'traitement_pre_jeu(etat_t *etat, int *a_deja_lancer_partie, player_t **j1, ordi_t **o, player_t *j2_distant, SDL_Texture *image[], int *ancien_lvl, character_t *tab_de_charactere, int *connexion_reussi, int *valide, int *resultat, SDL_Renderer *rendu):&#160;gestion.c']]]
];
